package br.com.gti.profectus.infra.common;

import java.io.Serializable;

/**
 * IMessage.
 * @author eduardo.fsantos
 * @since 08/05/2015
 */
public interface IProtocolMessage extends Serializable {

  /**
   * NAO CONECTADO MODULO ONLINE.
   */
  int MESSAGE_ERRO_CODE_CONNECTOR = 1;

  /**
   * ERROR FORMULA.
   */
  int MESSAGE_ERRO_CODE_ANTLR = 2;

  /**
   * .
   */
  int ORIGIN_SYSTEM_FEE = 1;

  /**
   * .
   */
  int ORIGIN_SYSTEM_TAX = 2;

  /**
   * TYPE_CALCULATION_REAL.
   */
  int TYPE_CALCULATION_REAL = 1;

  /**
   * TYPE_CALCULATION_PREVIOUS.
   */
  int TYPE_CALCULATION_PREVIOUS = 2;

  /**
   * ORIGIN_MESSAGE_ANYWHERE.
   */
  int ORIGIN_MESSAGE_ANYWHERE = 0;

  /**
   * ANYWHERE_TYPE_REQUEST_CALCULATE.
   */
  int ANYWHERE_TYPE_REQUEST_CALCULATE = 1;

  /**
   * ORIGIN_MESSAGE_NETTING.
   */
  int ORIGIN_MESSAGE_NETTING = 1;

  /**
   * ORIGIN_MESSAGE_MATRIX_OPERATION.
   */
  int ORIGIN_MESSAGE_MATRIX_OPERATION = 2;

  /**
   * ORIGIN_MESSAGE_MAINTENANCE.
   */
  int ORIGIN_MESSAGE_MAINTENANCE = 3;

  /**
   * ORIGIN_MESSAGE_ADMINISTRATOR.
   */
  int ORIGIN_MESSAGE_ADMINISTRATOR = 4;

  /**
   * ORIGIN_MESSAGE_TEST.
   */
  int ORIGIN_MESSAGE_TEST = 5;

  /**
   * ORIGIN_MESSAGE_SIMULATOR.
   */
  int ORIGIN_MESSAGE_SIMULATOR = 6;

  /**
   * ORIGIN_MESSAGE_LEGACY.
   */
  int ORIGIN_MESSAGE_LEGACY = 7;

  /**
   * NETTING_TYPE_REQUEST_CALCULATE.
   */
  int NETTING_TYPE_REQUEST_CALCULATE = 1;

  /**
   * NETTING_TYPE_REQUEST_CALCULATE_BASE_CALCULATION.
   */
  int NETTING_TYPE_REQUEST_CALCULATE_BASE_CALCULATION = 2;

  /**
   * NETTING_TYPE_REQUEST_CALCULATE_TAX.
   */
  int NETTING_TYPE_REQUEST_CALCULATE_TAX = 3;

  /**
   * NETTING_TYPE_REQUEST_RECALCULATE.
   */
  int NETTING_TYPE_REQUEST_RECALCULATE = 4;

  /**
   * NETTING_TYPE_REQUEST_CANCEL.
   */
  int NETTING_TYPE_REQUEST_CANCEL = 5;

  /**
   * MAINTENANCE_TYPE_REQUEST_VALIDATE_EQUATION.
   */
  int MAINTENANCE_TYPE_REQUEST_VALIDATE_EQUATION = 1;

  /**
   * MAINTENANCE_TYPE_REQUEST_GET_VARIABLES_OF_EQUATION.
   */
  int MAINTENANCE_TYPE_REQUEST_GET_VARIABLES_OF_EQUATION = 2;

  /**
   * MAINTENANCE_TYPE_REQUEST_GET_FUNCTIONS_OF_EQUATION.
   */
  int MAINTENANCE_TYPE_REQUEST_GET_FUNCTIONS_OF_EQUATION = 3;

  /**
   * TEST_TYPE_REQUEST_VALIDATE_EQUATION.
   */
  int TEST_TYPE_REQUEST_VALIDATE_EQUATION = 1;

  /**
   * TEST_TYPE_REQUEST_CALCULATE.
   */
  int TEST_TYPE_REQUEST_CALCULATE = 2;

  /**
   * SIMULATOR_TYPE_REQUEST_CALCULATE.
   */
  int SIMULATOR_TYPE_REQUEST_CALCULATE = 1;

  /**
   * MATRIX_OPERATION_TYPE_REQUEST_CALCULATE.
   */
  int MATRIX_OPERATION_TYPE_REQUEST_CALCULATE = 1;

  /**
   * MATRIX_OPERATION_TYPE_REQUEST_RECALCULATE.
   */
  int MATRIX_OPERATION_TYPE_REQUEST_RECALCULATE = 2;

  /**
   * MATRIX_OPERATION_TYPE_REQUEST_CANCEL.
   */
  int MATRIX_OPERATION_TYPE_REQUEST_CANCEL = 3;

  /**
   * LEGACY_TYPE_REQUEST_CALCULATE.
   */
  int LEGACY_TYPE_REQUEST_CALCULATE = 1;

  /**
   * LEGACY_TYPE_REQUEST_RECALCULATE.
   */
  int LEGACY_TYPE_REQUEST_RECALCULATE = 2;

  /**
   * LEGACY_TYPE_REQUEST_CANCEL.
   */
  int LEGACY_TYPE_REQUEST_CANCEL = 3;

}
